package com.ygxhj.mynetty.core.dao;

import com.ygxhj.mynetty.core.model.Player;
import com.ygxhj.mynetty.core.model.PlayerExample;
import java.sql.SQLException;
import java.util.List;

public interface PlayerDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player
	 * @abatorgenerated  Mon Jun 16 19:54:17 CST 2014
	 */
	Long insert(Player record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player
	 * @abatorgenerated  Mon Jun 16 19:54:17 CST 2014
	 */
	int updateByPrimaryKey(Player record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player
	 * @abatorgenerated  Mon Jun 16 19:54:17 CST 2014
	 */
	int updateByPrimaryKeySelective(Player record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player
	 * @abatorgenerated  Mon Jun 16 19:54:17 CST 2014
	 */
	List<Player> selectByExample(PlayerExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player
	 * @abatorgenerated  Mon Jun 16 19:54:17 CST 2014
	 */
	Player selectByPrimaryKey(Long id) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player
	 * @abatorgenerated  Mon Jun 16 19:54:17 CST 2014
	 */
	int deleteByExample(PlayerExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player
	 * @abatorgenerated  Mon Jun 16 19:54:17 CST 2014
	 */
	int deleteByPrimaryKey(Long id) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player
	 * @abatorgenerated  Mon Jun 16 19:54:17 CST 2014
	 */
	int countByExample(PlayerExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player
	 * @abatorgenerated  Mon Jun 16 19:54:17 CST 2014
	 */
	int updateByExampleSelective(Player record, PlayerExample example)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table player
	 * @abatorgenerated  Mon Jun 16 19:54:17 CST 2014
	 */
	int updateByExample(Player record, PlayerExample example)
			throws SQLException;
}