package com.ygxhj.mynetty.core.dao;

import com.ygxhj.mynetty.core.model.Product;
import com.ygxhj.mynetty.core.model.ProductExample;
import java.sql.SQLException;
import java.util.List;

public interface ProductDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	Integer insert(Product record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	int updateByPrimaryKey(Product record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	int updateByPrimaryKeySelective(Product record) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	List<Product> selectByExample(ProductExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	Product selectByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	int deleteByExample(ProductExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	int deleteByPrimaryKey(Integer id) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	int countByExample(ProductExample example) throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	int updateByExampleSelective(Product record, ProductExample example)
			throws SQLException;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table product
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	int updateByExample(Product record, ProductExample example)
			throws SQLException;
}