package com.ygxhj.mynetty.core.model;

import com.ibatis.common.beans.ProbeException;
import com.ygxhj.mynetty.core.BaseObject;

import java.util.Date;

public class Product extends BaseObject {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product.id
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product.product_id
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	private String productId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product.name
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product.create_time
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product.product_num
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	private Integer productNum;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product.destance
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	private String destance;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product.last_update
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	private Date lastUpdate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product.price
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	private Integer price;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product.discount
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	private Integer discount;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column product.deduct_price
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	private Integer deductPrice;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product.id
	 * @return  the value of product.id
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product.id
	 * @param id  the value for product.id
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product.product_id
	 * @return  the value of product.product_id
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	public String getProductId() {
		return productId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product.product_id
	 * @param productId  the value for product.product_id
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	public void setProductId(String productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product.name
	 * @return  the value of product.name
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product.name
	 * @param name  the value for product.name
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product.create_time
	 * @return  the value of product.create_time
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product.create_time
	 * @param createTime  the value for product.create_time
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product.product_num
	 * @return  the value of product.product_num
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	public Integer getProductNum() {
		return productNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product.product_num
	 * @param productNum  the value for product.product_num
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	public void setProductNum(Integer productNum) {
		this.productNum = productNum;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product.destance
	 * @return  the value of product.destance
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	public String getDestance() {
		return destance;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product.destance
	 * @param destance  the value for product.destance
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	public void setDestance(String destance) {
		this.destance = destance;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product.last_update
	 * @return  the value of product.last_update
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	public Date getLastUpdate() {
		return lastUpdate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product.last_update
	 * @param lastUpdate  the value for product.last_update
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product.price
	 * @return  the value of product.price
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	public Integer getPrice() {
		return price;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product.price
	 * @param price  the value for product.price
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product.discount
	 * @return  the value of product.discount
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	public Integer getDiscount() {
		return discount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product.discount
	 * @param discount  the value for product.discount
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	public void setDiscount(Integer discount) {
		this.discount = discount;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column product.deduct_price
	 * @return  the value of product.deduct_price
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	public Integer getDeductPrice() {
		return deductPrice;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column product.deduct_price
	 * @param deductPrice  the value for product.deduct_price
	 * @abatorgenerated  Thu Jun 12 17:55:04 CST 2014
	 */
	public void setDeductPrice(Integer deductPrice) {
		this.deductPrice = deductPrice;
	}

	public void addNumber(int number) throws ProbeException{
		if (number <= 0) {
			throw new ProbeException("add product number is less than 0");
		}
		productNum += number;
	}
	
	public void consumNumber(int number)throws ProbeException{
		if (number <= 0) {
			throw new ProbeException("consum product number is less than 0");
		}
		if (productNum < number) {
			throw new ProbeException(name + "ÊýÁ¿²»×ã£¡");
		}
		productNum -= number;
	}
	
	public String tableName = "product";
}